import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:silverhome/domain/entities/property_amenities.dart';
import 'package:silverhome/tablayer/tablePOJO.dart';

part 'events_types_state.freezed.dart';

@freezed
abstract class EventTypesState with _$EventTypesState {
  const factory EventTypesState({
    required List<SystemEnumDetails> propertytypelist,
    SystemEnumDetails? propertytypeValue,
    required String propertytypeOtherValue,
    required List<SystemEnumDetails> rentalspacelist,
    SystemEnumDetails? rentalspaceValue,
    required List<SystemEnumDetails> rentpaymentFrequencylist,
    SystemEnumDetails? rentpaymentFrequencyValue,
    required List<SystemEnumDetails> leasetypelist,
    SystemEnumDetails? leasetypeValue,
    required List<SystemEnumDetails> minimumleasedurationlist,
    SystemEnumDetails? minimumleasedurationValue,
    required String minimumleasedurationnumber,
    DateTime? dateofavailable,
    required String PropertyName,
    required String PropertyAddress,
    required String PropertyDescription,
    required String Suiteunit,
    required String Buildingname,
    required String City,
    required String Province,
    required String CountryName,
    required String CountryCode,
    required String Postalcode,
    required String RentAmount,

    /*Specification and Restriction*/
    required List<SystemEnumDetails> furnishinglist,
    SystemEnumDetails? furnishingValue,
    required List<SystemEnumDetails> restrictionlist,
    required String Other_Partial_Furniture,
    required String PropertyBedrooms,
    required String PropertyBathrooms,
    required String PropertySizeinsquarefeet,
    required String PropertyMaxoccupancy,

    /*Feature*/
    required List<PropertyAmenitiesUtility> propertyamenitieslist,
    required List<PropertyAmenitiesUtility> propertyutilitieslist,
    required List<SystemEnumDetails> storageavailablelist,
    SystemEnumDetails? storageavailableValue,
    required String Parkingstalls,
    required bool agree_TCPP,
    required int PropDrafting,
    required bool PropVacancy,
    required List<PropertyImageMediaInfo> propertyImagelist,

    /*Error Flag*/
    required bool error_propertytype,
    required bool error_propertytypeOther,
    required bool error_rentalspace,
    required bool error_rentpaymentFrequency,
    required bool error_leasetype,
    required bool error_minimumleaseduration,
    required bool error_minimumleasedurationnumber,
    required bool error_dateofavailable,
    required bool error_PropertyName,
    required bool error_PropertyAddress,
    required bool error_City,
    required bool error_Province,
    required bool error_CountryName,
    required bool error_Postalcode,
    required bool error_RentAmount,
    required bool error_furnishing,
    required bool error_Other_Partial_Furniture,
    required bool error_PropertyBedrooms,
    required bool error_PropertyBathrooms,
    required bool error_PropertySizeinsquarefeet,
    required bool error_PropertyMaxoccupancy,
    required bool error_storageavailable,
    required bool error_Parkingstalls,
  }) = _EventTypesState;

  factory EventTypesState.initial() => EventTypesState(
        propertytypelist: List.empty(),
        propertytypeValue: null,
        propertytypeOtherValue: "",
        rentalspacelist: List.empty(),
        rentalspaceValue: null,
        rentpaymentFrequencylist: List.empty(),
        rentpaymentFrequencyValue: null,
        leasetypelist: List.empty(),
        leasetypeValue: null,
        minimumleasedurationlist: List.empty(),
        minimumleasedurationValue: null,
        minimumleasedurationnumber: "",
        dateofavailable: null,
        PropertyName: "",
        PropertyAddress: "",
        PropertyDescription: "",
        Suiteunit: "",
        Buildingname: "",
        City: "",
        Province: "",
        CountryName: "Canada",
        CountryCode: "CA",
        Postalcode: "",
        RentAmount: "",
        furnishinglist: List.empty(),
        furnishingValue: null,
        restrictionlist: List.empty(),
        Other_Partial_Furniture: "",
        PropertyBedrooms: "",
        PropertyBathrooms: "",
        PropertySizeinsquarefeet: "",
        PropertyMaxoccupancy: "",
        propertyamenitieslist: List.empty(),
        propertyutilitieslist: List.empty(),
        storageavailablelist: List.empty(),
        storageavailableValue: null,
        Parkingstalls: "",
        agree_TCPP: false,
        PropDrafting: 0,
        PropVacancy: false,
        propertyImagelist: List.empty(),

        /*Error Flag*/
        error_propertytype: false,
        error_propertytypeOther: false,
        error_rentalspace: false,
        error_rentpaymentFrequency: false,
        error_leasetype: false,
        error_minimumleaseduration: false,
        error_minimumleasedurationnumber: false,
        error_dateofavailable: false,
        error_PropertyName: false,
        error_PropertyAddress: false,
        error_City: false,
        error_Province: false,
        error_CountryName: false,
        error_Postalcode: false,
        error_RentAmount: false,
        error_furnishing: false,
        error_Other_Partial_Furniture: false,
        error_PropertyBedrooms: false,
        error_PropertyBathrooms: false,
        error_PropertySizeinsquarefeet: false,
        error_PropertyMaxoccupancy: false,
        error_storageavailable: false,
        error_Parkingstalls: false,
      );
}
